const imagePresets = {
  logo: {
    width: 337,
    height: 80,
    fit: 'contain',
    background: { r: 0, g: 0, b: 0, alpha: 0 },
    format: 'png',
    folder: 'logos',
  },
  icon: {
    width: 64,
    height: 64,
    fit: 'contain',
    background: { r: 0, g: 0, b: 0, alpha: 0 },
    format: 'png',
    folder: 'icons',
  },
  avatar: {
    width: 200,
    height: 200,
    fit: 'cover',
    format: 'webp',
    folder: 'avatars',
  },
  testimonial: {
    width: 150,
    height: 150,
    fit: 'cover',
    format: 'webp',
    folder: 'testimonials',
  },
  team: {
    width: 640,
    height: 640,
    fit: 'cover',
    format: 'webp',
    folder: 'team',
  },
  card: {
    width: 800,
    height: 800,
    fit: 'cover',
    format: 'webp',
    folder: 'cards',
  },
  hero: {
    width: 1920,
    height: 945,
    fit: 'cover',
    format: 'webp',
    folder: 'hero',
  },
  banner: {
    width: 1920,
    height: 800,
    fit: 'cover',
    format: 'webp',
    folder: 'banners',
  },
  illustration: {
    width: 1200,
    fit: 'inside',
    format: 'webp',
    folder: 'illustrations',
  },
  screenshot: {
    width: 750,
    height: 1334,
    fit: 'cover',
    format: 'webp',
    folder: 'screenshots',
  },
  phoneScreenshot: {
    width: 441,
    height: 955,
    fit: 'cover',
    format: 'webp',
    folder: 'screenshots',
  },
  qr: {
    width: 400,
    height: 400,
    fit: 'contain',
    background: { r: 255, g: 255, b: 255, alpha: 1 },
    format: 'png',
    folder: 'qr',
  },
  clientLogo: {
    width: 220,
    height: 60,
    fit: 'contain',
    background: { r: 0, g: 0, b: 0, alpha: 0 },
    format: 'png',
    folder: 'client-logos',
  },
  general: {
    width: 1600,
    fit: 'inside',
    format: 'webp',
    folder: 'general',
  },
}

module.exports = {
  imagePresets,
}
